// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knojozolqaumqtvoojef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtub2pvem9scWF1bXF0dm9vamVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTc1ODgsImV4cCI6MjA2Nzg3MzU4OH0.Q3jkcDnrQhcE4azj29Na4RREagOEYu1fJEK4bmxE5fw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});